#!/bin/sh

#サービス名
MINECRAFT_SERVER_SERVICE_NAME="minecraft_server"

#サービス実行ユーザ名
MINECRAFT_SERVER_EXECUTE_USER="minecraft"

#サービス実行グループ名
MINECRAFT_SERVER_EXECUTE_GROUP="minecraft"

#サービス実行ルートディレクトリパス
#MINECRAFT_SERVER_ROOT=""

#JQコマンドパス TODO:今のところ使ってない
#JQ_PATH=""

#tarコマンドパス
#TAR_PATH=""

#curlコマンドパス
#CURL_PATH=""

#gitコマンドパス
#GIT_PATH=""

#JAVAパス
#JAVA_PATH=""

#予約最小メモリ
MIN_MEMORY="1024M"

#使用最大メモリ
MAX_MEMORY="4096M"

#JARファイルパス
JAR_PATH="/usr/local/lib/minecraft_server/minecraft_server.jar"

#サーバタイプ(例:spigot,papermc)
SERVER_TYPE="papermc"

#サーバーのバージョン
SERVER_REVISION="1.21.11"

#終了ウェイトタイム
DEFAULT_STOP_WATE_TIME=60

#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).
eula=true

#ビルド用一時ディレクトリ
BUILD_DIR="/tmp/minecraft_server/build/"
