#!/bin/sh

#サービス名
MINECRAFT_SERVER_SERVICE_NAME="minecraft_server"

#サービス実行ユーザ名
MINECRAFT_SERVER_EXECUTE_USER="minecraft"

#サービス実行グループ名
MINECRAFT_SERVER_EXECUTE_GROUP="minecraft"

#サービス実行ルートディレクトリパス
MINECRAFT_SERVER_ROOT="/var/minecraft_server"

#curlコマンドパス
CURL_PATH="/usr/local/bin/curl"

#screenコマンドのパス
SCREEN_PATH="/usr/local/bin/screen"

#サービス実行スクリーン名
SCREEN_NAME="minecraft_server"

#JVMパス
JVM_PATH="/usr/local/bin/java"

#予約最小メモリ
MIN_MEMORY="1024M"

#使用最大メモリ
MAX_MEMORY="4096M"

#JARファイルパス
JAR_PATH="/usr/local/lib/minecraft_server/minecraft_server.jar"

#サーバタイプ(例:craftbukkit,spigot)
SERVER_TYPE="craftbukkit"

#サーバーのバージョン
SERVER_REVISION="1.14.4"

#終了ウェイトタイム
DEFAULT_STOP_WATE_TIME=60

#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).
eula=false