#!/bin/sh

. [[[SERVICE_CONFIG_DIR]]]/[[[MINECRAFT_SERVER_SERVICE_NAME]]]
. [[[SERVICE_LIB_DIR]]]/FUNC_EXECCOMMAND

FUNC_START(){
	cd ${MINECRAFT_SERVER_ROOT}
	[[[TMUX_PATH]]] new-session -d -s ${TMUX_NAME} sh -c "[[[SUDO_PATH]]] -u ${MINECRAFT_SERVER_EXECUTE_USER} [[[JAVA_PATH]]] -server -Xms${MIN_MEMORY} -Xmx${MAX_MEMORY} -jar ${JAR_PATH} nogui; [[[TMUX_PATH]]] kill-session -t ${TMUX_NAME}"
}
