#!/bin/sh

. [[[SERVICE_CONFIG_DIR]]]/[[[MINECRAFT_SERVER_SERVICE_NAME]]]
. [[[SERVICE_LIB_DIR]]]/FUNC_BUILD
. [[[SERVICE_LIB_DIR]]]/FUNC_COMMON
. [[[SERVICE_LIB_DIR]]]/FUNC_EXECCOMMAND
. [[[SERVICE_LIB_DIR]]]/FUNC_REMOVE

execute_file_path="$(cd $(dirname $0) && pwd)/$(basename $0)"
execute_paramator="$@"

switch_execute_user "Sudo is required to this script execute. Please input your account password." "Need root parmissions for this script execute." ${execute_file_path} ${execute_paramator}
user_check_result=$?
if [ ${user_check_result} -eq 2 ]; then
	exit 0
elif [ ${user_check_result} -eq 1 ]; then
	exit 1
fi

case "$1" in
build)
	FUNC_BUILD
;;
command)
	FUNC_EXECCOMMAND "$2"
;;
disable)
	systemctl disable ${MINECRAFT_SERVER_SERVICE_NAME}
;;
enable)
	systemctl enable ${MINECRAFT_SERVER_SERVICE_NAME}
;;
remove)
	FUNC_REMOVE
;;
restart)
	systemctl stop ${MINECRAFT_SERVER_SERVICE_NAME}
	systemctl start ${MINECRAFT_SERVER_SERVICE_NAME}
;;
start)
	systemctl start ${MINECRAFT_SERVER_SERVICE_NAME}
;;
status)
	systemctl status ${MINECRAFT_SERVER_SERVICE_NAME}
;;
stop)
	systemctl stop ${MINECRAFT_SERVER_SERVICE_NAME}
;;
*)
echo $"Usage: $0 {build|command|disable|enable|restart|start|stop}"
exit 1
esac
exit 0
