#!/bin/sh

. [[[SERVICE_CONFIG_DIR]]]/[[[MINECRAFT_SERVER_SERVICE_NAME]]]
. [[[SERVICE_LIB_DIR]]]/FUNC_EXECCOMMAND

FUNC_STOP(){
	FUNC_EXECCOMMAND "save-all"
	if [ $? -eq 0 ]; then
		while [ ${DEFAULT_STOP_WATE_TIME} -ne 0 ]; do
			if [ `expr ${DEFAULT_STOP_WATE_TIME} % 30` -eq 0 -o ${DEFAULT_STOP_WATE_TIME} -le 10 ]; then
			FUNC_EXECCOMMAND "say Server will stop in ${DEFAULT_STOP_WATE_TIME} seconds."
		fi
		DEFAULT_STOP_WATE_TIME=`expr ${DEFAULT_STOP_WATE_TIME} - 1`
		sleep 1
	done
	FUNC_EXECCOMMAND "stop"
	fi
}
