#!/bin/sh

. [[[SERVICE_CONFIG_DIR]]]/[[[MINECRAFT_SERVER_SERVICE_NAME]]]
. [[[SERVICE_LIB_DIR]]]/FUNC_EXECCOMMAND

FUNC_START(){
	echo -n $"Starting ${MINECRAFT_SERVER_SERVICE_NAME} daemon:"
	FUNC_EXECCOMMAND '' >& /dev/null
	if test $? -eq 1
	then
		cd ${MINECRAFT_SERVER_ROOT}
		${SCREEN_PATH} -AmdS ${SCREEN_NAME} sudo -u ${MINECRAFT_SERVER_EXECUTE_USER} ${JVM_PATH} -server -Xms${MIN_MEMORY} -Xmx${MAX_MEMORY} -jar ${JAR_PATH} nogui
		echo_success
		touch /var/lock/subsys/${MINECRAFT_SERVER_SERVICE_NAME}
	else
		echo_passed
	fi
	printf "\n"
}