#!/bin/sh

. [[[SERVICE_CONFIG_DIR]]]/[[[MINECRAFT_SERVER_SERVICE_NAME]]]
. [[[SERVICE_LIB_DIR]]]/FUNC_BUILD
. [[[SERVICE_LIB_DIR]]]/FUNC_EXECCOMMAND
. [[[SERVICE_LIB_DIR]]]/FUNC_REMOVE

case "$1" in
build)
	FUNC_BUILD
;;
command)
	FUNC_EXECCOMMAND "$2"
;;
remove)
	FUNC_REMOVE
;;
restart)
	service ${MINECRAFT_SERVER_SERVICE_NAME} stop
	service ${MINECRAFT_SERVER_SERVICE_NAME} start
;;
start)
	service ${MINECRAFT_SERVER_SERVICE_NAME} start
;;
status)
	service ${MINECRAFT_SERVER_SERVICE_NAME} status
;;
stop)
	service ${MINECRAFT_SERVER_SERVICE_NAME} stop
;;
*)
echo $"Usage: $0 {build|command|restart|start|stop}"
exit 1
esac
exit 0
