#!/bin/sh
# chkconfig:345 99 01
# description: [[[MINECRAFT_SERVER_SERVICE_NAME]]]

. /etc/rc.d/init.d/functions
. [[[SERVICE_LIB_DIR]]]/FUNC_COMMON
. [[[SERVICE_LIB_DIR]]]/FUNC_START
. [[[SERVICE_LIB_DIR]]]/FUNC_STOP
. [[[SERVICE_LIB_DIR]]]/FUNC_RESTART
. [[[SERVICE_LIB_DIR]]]/FUNC_RELOAD

execute_file_path="$(cd $(dirname $0) && pwd)/$(basename $0)"
execute_paramator="$@"

switch_execute_user "Sudo is required to this script execute. Please input your account password." "Need root parmissions for this script execute." ${execute_file_path} ${execute_paramator}
user_check_result=$?
if [ ${user_check_result} -eq 2 ]; then
	exit 0
elif [ ${user_check_result} -eq 1 ]; then
	exit 1
fi

case "$1" in
start)
	FUNC_START
;;
stop)
	FUNC_STOP
;;
restart)
	FUNC_RESTART
;;
status)
	status -l ${MINECRAFT_SERVER_SERVICE_NAME} ${MINECRAFT_SERVER_SERVICE_NAME}
;;
reload)
	FUNC_RELOAD
;;
*)
echo $"Usage: $0 {start|stop|reload|restart}"
exit 1
esac
exit 0
