#!/bin/sh

. [[[SERVICE_CONFIG_DIR]]]/[[[MINECRAFT_SERVER_SERVICE_NAME]]]
. [[[SERVICE_LIB_DIR]]]/FUNC_BUILD
. [[[SERVICE_LIB_DIR]]]/FUNC_COMMON
. [[[SERVICE_LIB_DIR]]]/FUNC_REMOVE
DMNG_JSON="[[[SERVICE_LIB_DIR]]]/dmng.json"

execute_file_path="$(cd $(dirname $0) && pwd)/$(basename $0)"
execute_paramator="$@"

switch_execute_user "Sudo is required to this script execute. Please input your account password." "Need root parmissions for this script execute." "${execute_file_path}" "${execute_paramator}"
user_check_result="${?}"
if [ "${user_check_result}" -eq 2 ]; then
	exit 0
elif [ "${user_check_result}" -eq 1 ]; then
	exit 1
fi

DMNG_JSON_STR=$(cat "${DMNG_JSON}")
if [ -z "${DMNG_JSON_STR}" ]; then
	echo "Error: Failed to read dmng.json. Please check the file content."
	exit 1
fi

case "${1}" in
	#TODO:BACKUPを作る
	build)
		FUNC_BUILD
	;;
	#TODO:COMMANDを作る
	disable)
		EXECUTE_COMMAND=$(get_daemon_json_value "disable" ${DMNG_JSON_STR})
	;;
	enable)
		EXECUTE_COMMAND=$(get_daemon_json_value "enable" ${DMNG_JSON_STR})
	;;
	remove)
		FUNC_REMOVE
		exit ${?}
	;;
	restart)
		EXECUTE_COMMAND=$(get_daemon_json_value "restart" ${DMNG_JSON_STR})
	;;
	#TODO:SNAPSHOTを作る
	start)
		EXECUTE_COMMAND=$(get_daemon_json_value "start" ${DMNG_JSON_STR})
	;;
	status)
		EXECUTE_COMMAND=$(get_daemon_json_value "status" ${DMNG_JSON_STR})
	;;
	stop)
		EXECUTE_COMMAND=$(get_daemon_json_value "stop" ${DMNG_JSON_STR})
	;;
	*)
	echo "Usage: ${0} {build|disable|enable|restart|start|stop}"
	exit 1
esac

if [ -z "${EXECUTE_COMMAND}" ]; then
	echo "Error: Failed to read command from dmng.json. Please check the file content."
	exit 1
fi

eval "${EXECUTE_COMMAND}"

exit ${?}
